export const GET_ALL_DISH_REQUEST = 'GET_ALL_DISH_REQUEST';
export const GET_ALL_DISH_SUCCESS = 'GET_ALL_DISH_SUCCESS';
export const GET_ALL_DISH_FAILURE = 'GET_ALL_DISH_FAILURE';

export const GET_DISH_REQUEST = 'GET_DISH_REQUEST';
export const GET_DISH_SUCCESS = 'GET_DISH_SUCCESS';
export const GET_DISH_FAILURE = 'GET_DISH_FAILURE';